services:
  - type: web
    name: invisible-recaptcha-validator
    runtime: node
    plan: starter
    region: ohio
    repo: https://github.com/markhillard/invisible-recaptcha-validator.git
    branch: master
    buildCommand: yarn
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: PORT
        sync: false
      - key: RECAPTCHA_SECRET
        sync: false
